version: '2'
services:

  compiler-app:
    container_name: compiler-app
    image: node:8.7.0
    volumes:
      - $PWD/:/app
      - $PWD/../build/:/app/node_modules/react-push-state
    working_dir: /app

  # Run the app
  react-state-sample:
    extends: compiler-app
    container_name: react-state
    hostname: sample1.react-state.dev
    command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    network_mode: bridge